<?php

return [
    'dimensions' => [
        'attachment_security' => '依恋安全感',
        'social_energy' => '社交能量',
        'communication_directness' => '沟通直接度',
        'emotional_stability' => '情绪稳定度',
        'planning_style' => '计划倾向',
    ],
    'matching_weights' => [
        'attachment_security' => 1.3,
        'social_energy' => 1.0,
        'communication_directness' => 1.2,
        'emotional_stability' => 1.4,
        'planning_style' => 1.1,
    ],
    'complementary_dimensions' => [
        'social_energy',
    ],

    'question_scoring' => [
        'doc_value_1' => [
            'A' => ['attachment_security' => 2, 'planning_style' => 1],
            'B' => ['attachment_security' => 1, 'emotional_stability' => 1],
            'C' => ['communication_directness' => -1],
            'D' => ['communication_directness' => -2, 'emotional_stability' => -1],
            '这是诚信问题，绝对不能接受' => ['attachment_security' => 2, 'planning_style' => 1],
            '可以理解，但自己不会这么做' => ['attachment_security' => 1, 'emotional_stability' => 1],
            '只要能力匹配，简历美化无伤大雅' => ['communication_directness' => -1],
            '招聘本身就是博弈，这很正常' => ['communication_directness' => -2, 'emotional_stability' => -1],
        ],
        'doc_value_2' => [
            'A' => ['communication_directness' => 2, 'attachment_security' => 1],
            'B' => ['communication_directness' => 1],
            'C' => ['communication_directness' => -1, 'emotional_stability' => -1],
            'D' => ['planning_style' => 1, 'emotional_stability' => 1],
            '必须说，朋友有知情权' => ['communication_directness' => 2, 'attachment_security' => 1],
            '委婉暗示，让朋友自己发现' => ['communication_directness' => 1],
            '不说，说了朋友会痛苦，还可能怪我' => ['communication_directness' => -1, 'emotional_stability' => -1],
            '看情况，如果快结婚了就说' => ['planning_style' => 1, 'emotional_stability' => 1],
        ],
        'doc_value_3' => [
            'A' => ['communication_directness' => 2],
            'B' => ['communication_directness' => -1],
            'C' => ['planning_style' => 1],
            'D' => ['communication_directness' => -2, 'emotional_stability' => -1],
            '直接沟通，表达不满' => ['communication_directness' => 2],
            '自己多做点，懒得冲突' => ['communication_directness' => -1],
            '默默减少交流，考虑换室友' => ['planning_style' => 1],
            '在朋友圈发“有些人真的不懂尊重”' => ['communication_directness' => -2, 'emotional_stability' => -1],
        ],
        'doc_value_4' => [
            'A' => ['attachment_security' => 1, 'planning_style' => 1],
            'B' => ['planning_style' => 2],
            'C' => ['emotional_stability' => 1],
            'D' => ['social_energy' => 2],
            '给父母买房/还贷' => ['attachment_security' => 1, 'planning_style' => 1],
            '投资自己（留学/进修/创业）' => ['planning_style' => 2],
            '存起来，当作安全感' => ['emotional_stability' => 1],
            '吃喝玩乐，享受生活' => ['social_energy' => 2],
        ],
        'doc_value_5' => [
            'A' => ['planning_style' => 1],
            'B' => ['attachment_security' => 2],
            'C' => ['planning_style' => -1, 'emotional_stability' => -1],
            'D' => ['attachment_security' => -1],
            '工作多年，收入不如同龄人' => ['planning_style' => 1],
            '和家人关系疏远，没人理解自己' => ['attachment_security' => 2],
            '找不到人生方向，混一天是一天' => ['planning_style' => -1, 'emotional_stability' => -1],
            '朋友们都成家立业，自己还是一个人' => ['attachment_security' => -1],
        ],
        'doc_value_6' => [
            'A' => ['planning_style' => 2, 'social_energy' => 1],
            'B' => ['planning_style' => 1, 'emotional_stability' => 1],
            'C' => ['planning_style' => 0, 'emotional_stability' => 0],
            'D' => ['emotional_stability' => 2],
            '全力争取，年轻就该拼' => ['planning_style' => 2, 'social_energy' => 1],
            '会争取，但也要看身体是否扛得住' => ['planning_style' => 1, 'emotional_stability' => 1],
            '犹豫，不想牺牲生活品质' => ['planning_style' => 0, 'emotional_stability' => 0],
            '放弃，健康和生活更重要' => ['emotional_stability' => 2],
        ],
        'doc_value_7' => [
            'A' => ['communication_directness' => 2],
            'B' => ['communication_directness' => 1],
            'C' => ['communication_directness' => -1],
            'D' => ['planning_style' => 1, 'attachment_security' => -1],
            '直接开口要，钱是钱，朋友是朋友' => ['communication_directness' => 2],
            '委婉提醒，比如“最近手头紧”' => ['communication_directness' => 1],
            '等对方主动还，不好意思催' => ['communication_directness' => -1],
            '就当送TA了，以后不再借' => ['planning_style' => 1, 'attachment_security' => -1],
        ],
        'doc_value_8' => [
            'A' => ['planning_style' => 1],
            'B' => ['attachment_security' => 2],
            'C' => ['attachment_security' => 1, 'emotional_stability' => 1],
            'D' => ['communication_directness' => -1],
            '不害人，遵纪守法' => ['planning_style' => 1],
            '愿意帮助别人，哪怕自己吃亏' => ['attachment_security' => 2],
            '对得起自己，也对得起在乎的人' => ['attachment_security' => 1, 'emotional_stability' => 1],
            '世界复杂，没法简单定义好人坏人' => ['communication_directness' => -1],
        ],
        'doc_value_9' => [
            'A' => ['attachment_security' => 2, 'emotional_stability' => 1],
            'B' => ['attachment_security' => 1],
            'C' => ['attachment_security' => -2],
            'D' => ['planning_style' => 0],
            '内心不安，可能还是会坦白' => ['attachment_security' => 2, 'emotional_stability' => 1],
            '会内疚，但时间长了就忘了' => ['attachment_security' => 1],
            '既然没人知道，就当没发生' => ['attachment_security' => -2],
            '看是什么错，小事无所谓' => ['planning_style' => 0],
        ],
        'doc_value_10' => [
            'A' => ['attachment_security' => 2, 'communication_directness' => 1],
            'B' => ['planning_style' => 1],
            'C' => ['communication_directness' => -1],
            'D' => ['communication_directness' => 0],
            '坚决反对，手段决定目的的性质' => ['attachment_security' => 2, 'communication_directness' => 1],
            '看目的，如果目的是好的，可以理解' => ['planning_style' => 1],
            '现实世界就是这样，太干净成不了事' => ['communication_directness' => -1],
            '不评价，每个人有自己的活法' => ['communication_directness' => 0],
        ],
    ],
];
